version: 2

sources:
  - name: raw
    description: "Raw ASOS dataset loaded into Snowflake."

    database: ASOS_DB
    schema: RAW

    tables:
      - name: ASOS_PRODUCTS_RAW
        description: "Original ASOS products dataset."
